# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Pedro Alvarez
tagline:             Software Engineer
url:                 http://jekyll.alvarezpiedehierro.com
paginate:            4
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Pedro Alvarez Piedehierro
  url:               https://twitter.com/palvarez1989
  email:             palvarez89@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/palvarez89

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
